# Site
title:              记录的地方
bio:                '就算明天还是扑朔的，睁开眼，看天空转色。'
description:        "没有啥介绍和标签，只是在这里表达"
reading_time:       false
words_per_minute:   88
logo:               'assets/img/logo.png'
background:         false
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zh_CN
url:                http://chenwen.site

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
  #disqus_shortname: vinechen
  # Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : vinechen
# comments:
# provider: duoshuo
# duoshuo:
# short_name: vinechen
# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-82676305-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            vine1024
#facebook:           username
#github:             vinechen
email:              vinebyte@gmail.com
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:              234960910
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
