# Site
title:              Vine Chen
bio:                'Know Yourself'
description:        "一个手指特长的人."
reading_time:       true
words_per_minute:   20
logo:               'assets/img/logo.png'
background:         false
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zh_CN
url:                http://vinechen.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Comments
comments :
provider : duoshuo
duoshuo :
short_name : vinechen

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#hackernews:        username
#facebook:
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            ideameet
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
twitter:            IdeaMeet
weibo:             234960910
github:             vinechen
email:            newnehc@live.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: html://vinechen.github.io

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
